# INFO 212: Data Science Programming 1
## CCI at Drexel University


## Week 3: Lab: Numpy and Pandas


In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


## What to do:
- Answer each question individually.
- Comment on each single statement.
- Each missing comment will be penalized by 1 point.
- Verify the code by showing meaningful results.

import packages

In [23]:
import random  # Importing the randon library
import numpy as np  # Importing the numpy library as np
import pandas as pd  # Importing the pandas library as pd

## Exercise 1:

Create 3 lists, `ls1`, `ls2`, and `ls3`, with the following values:
- `ls1` contains 10 random decimal numbers in the range of (0.00, 150.00), each of which with 2-digit precision.
- `ls2` contains 10 random integers in the range of (1, 500).
- `ls3` contains 10 random decimal numbers in the range of (0.05, 0.90), each of which with 2-digit precision and the last digit rounded to the nearest 0 or 5.

Show the content of the lists.

In [24]:
def float_number_generator(lower_range, upper_range, step):  # Defining function for getting ls1, ls3. Takes 3 input parameters.
  if step != 0:  # Executes code for generation of ls3
    total_numbers_in_list = np.arange(lower_range, upper_range, step)  # Gets all the numbers between the lower range, upper range but in intervals of the 'step'
    random_index = [random.randint(0, len(total_numbers_in_list) -1) for i in range(10)]  # List Comprehension - Getting the index value of the numbers that we will be selecting from 'total_numbers_in_list'. A loop runs for 10 iterations since we only need 10 numbers hence only 10 index positions
    ls = [round(total_numbers_in_list[i], 2) for i in random_index]  # From 'total_numbers_in_list', we select those numbers that our random index generator has generated, and we do that for every index value in the 'random_index' list
    return ls  # Returning the list formed. In this case, ls3
  else:  # Executes code for generation of ls1
    return [round(random.uniform(0.00, 150.00), 2) for i in range(10)]  # List comprehension - Getting 10 random float numbers between 0.00 and 150.00 rounded up to 2 decimal places

ls1 = float_number_generator(0.00, 150.00, 0)  # Calls the function for storing the list
ls2 = [random.randint(1, 500) for i in range(10)]  # Runs the loop 10 times to get 10 random integer numbers between 1 and 500
ls3 = float_number_generator(0.05, 0.90, 0.05)  # Calls the function for storing the list

print(f"ls1: {ls1}")  # Prints the content of the list
print(f"ls2: {ls2}")  # Prints the content of the list
print(f"ls3: {ls3}")  # Prints the content of the list

ls1: [76.29, 82.04, 7.66, 28.8, 41.18, 4.93, 77.0, 29.38, 145.03, 50.26]
ls2: [394, 170, 408, 403, 245, 471, 487, 103, 3, 429]
ls3: [0.75, 0.3, 0.2, 0.85, 0.4, 0.25, 0.4, 0.05, 0.55, 0.55]


## Exercise 2:
- Use the 3 lists as 3 columns to create a numpy array `arr` which uses `ls1` as the first column, `ls2` as the second column, and `ls3` as the third column.
- Show the content and shape of the array.

In [25]:
arr = np.array([[ls1[i], ls2[i], ls3[i]] for i in range(10)])  # Creating a numpy array called arr which stores the contents of the 3 lists generated above as an array. For loop used since we have 10 elements per list and need 10 rows. The array stores items per row

print(f"Content: \n{arr}\n")  # Prints the content of the arr
print(f"Shape: {arr.shape}")  # Prints the shape of the arr. (10 rows and 3 columns)

Content: 
[[7.6290e+01 3.9400e+02 7.5000e-01]
 [8.2040e+01 1.7000e+02 3.0000e-01]
 [7.6600e+00 4.0800e+02 2.0000e-01]
 [2.8800e+01 4.0300e+02 8.5000e-01]
 [4.1180e+01 2.4500e+02 4.0000e-01]
 [4.9300e+00 4.7100e+02 2.5000e-01]
 [7.7000e+01 4.8700e+02 4.0000e-01]
 [2.9380e+01 1.0300e+02 5.0000e-02]
 [1.4503e+02 3.0000e+00 5.5000e-01]
 [5.0260e+01 4.2900e+02 5.5000e-01]]

Shape: (10, 3)


## Exercise 3:
- For the third column of `arr`, compute a boolean array indicating whether the value is between [0.20, 0.50].
- Use the boolean array to extract the rows of `arr` such as the values of the third column are between [0.20, 0.50].

In [26]:
boolean_array = []  # Creating an empty list that will store the true/false if numbers is between [0.20, 0.50]
new_ls3 = []  # Creating an empty list that will store the numbers that are between [0.20, 0.50]

for num in ls3:  # Runs the loop for every number in ls3
  if ((num  >= 0.20) and (num <= 0.50)):  # Checks if the number in ls3 is between [0.20, 0.50]
    boolean_array.append("true")  # If condition satisfied, then we add 'true' to the list
    new_ls3.append(num)  # If condition satisfied, we add the number to the new list
  else:  # Is executed if the number in ls3 is not between [0.20, 0.50]
    boolean_array.append("false")  # Adds 'false' to the list

print(f"Boolean Array: {boolean_array}\n")  # Prints the contents of the boolean_array
print(f"Extracting only those rows for which Boolean Array is 'true': {new_ls3}")  # Prints the contents of the new_ls3

Boolean Array: ['false', 'true', 'true', 'false', 'true', 'true', 'true', 'false', 'false', 'false']

Extracting only those rows for which Boolean Array is 'true': [0.3, 0.2, 0.4, 0.25, 0.4]


## Exercise 4:

Use `ls1`, `ls2`, and `ls3` as the three columns to create a Pandas DataFrame `items`. Assign the column names as `['price', 'quantity', 'discount']`.

In [27]:
items = pd.DataFrame(arr)  # Creating a pandas dataframe by using the arr created above
items.columns = ['price', 'quantity', 'discount']  # Assigning the column names to the required ones

print(items)  # Displaying the contents

    price  quantity  discount
0   76.29     394.0      0.75
1   82.04     170.0      0.30
2    7.66     408.0      0.20
3   28.80     403.0      0.85
4   41.18     245.0      0.40
5    4.93     471.0      0.25
6   77.00     487.0      0.40
7   29.38     103.0      0.05
8  145.03       3.0      0.55
9   50.26     429.0      0.55


## Exercise 5:

Show the shape, columns, and summary statistics of the DataFrame `items`.

In [29]:
print(f"Shape: {items.shape}\n")  # Displaying the shape of the new dataframe 'items'
print(f"Columns: \n{items.columns} \n")  # Displaying the Column names of the new dataframe
print(f"Summary statistics: \n{items.describe()}")  # Displaying the summary of the statistics of the dataframe using the describe() function

Shape: (10, 3)

Columns: 
Index(['price', 'quantity', 'discount'], dtype='object') 

Summary statistics: 
            price    quantity   discount
count   10.000000   10.000000  10.000000
mean    54.257000  311.300000   0.430000
std     42.259346  169.189604   0.248551
min      4.930000    3.000000   0.050000
25%     28.945000  188.750000   0.262500
50%     45.720000  398.500000   0.400000
75%     76.822500  423.750000   0.550000
max    145.030000  487.000000   0.850000


## Exercise 6:

Create a list of 10 strings as item names (meaningful names). Assign the names to the index of the DataFrame `items`. Show the final DataFrame.

In [32]:
index_names = ["Alex", "Bob", "Charlie", "Don", "Ethan", "Frankfurt", "Goodwin", "Harry", "Ian", "Joseph"]  # Creating a list with 10 names
items.index = index_names  # Assigning the above names as the index of the 'items' dataframe

print(items)  # Displaying the final dataframe

            price  quantity  discount
Alex        76.29     394.0      0.75
Bob         82.04     170.0      0.30
Charlie      7.66     408.0      0.20
Don         28.80     403.0      0.85
Ethan       41.18     245.0      0.40
Frankfurt    4.93     471.0      0.25
Goodwin     77.00     487.0      0.40
Harry       29.38     103.0      0.05
Ian        145.03       3.0      0.55
Joseph      50.26     429.0      0.55
